#ifndef _VXSDR_DMA_CMD_H
#define _VXSDR_DMA_CMD_H

#define VXSDR_DMA_DRIVER_VERSION "2.03"

#define ALTERA_DMA_DID 0xE003
#define ALTERA_DMA_VID 0x1172

#define VXSDR_DMA_TX_BUF_CNT_MAX 128
#define VXSDR_DMA_RX_BUF_CNT_MAX 512

#include <linux/ioctl.h>

#define ALTERA_IOC_MAGIC   0x66

#define IOCTL_MMAP_TX_SEL                 _IO(ALTERA_IOC_MAGIC, 20)
#define IOCTL_TX_WAIT_DONE                _IO(ALTERA_IOC_MAGIC, 21)
#define IOCTL_CHECKOUT_TX_BUFFER          _IO(ALTERA_IOC_MAGIC, 22)
#define IOCTL_UPLOAD_TX_BUFFER_BLOCKING   _IO(ALTERA_IOC_MAGIC, 23)
#define IOCTL_RELEASE_TX_BUFFER           _IO(ALTERA_IOC_MAGIC, 24)
#define IOCTL_CHECKOUT_RX_BUFFER_BLOCKING _IO(ALTERA_IOC_MAGIC, 25)
#define IOCTL_RELEASE_RX_BUFFER           _IO(ALTERA_IOC_MAGIC, 26)
#define IOCTL_TX_BLOCK_TIMEOUT            _IO(ALTERA_IOC_MAGIC, 27)
#define IOCTL_RX_BLOCK_TIMEOUT            _IO(ALTERA_IOC_MAGIC, 28)
#define IOCTL_TX_IOCTL_BLOCK_TIMEOUT      _IO(ALTERA_IOC_MAGIC, 29)
#define IOCTL_RX_IOCTL_BLOCK_TIMEOUT      _IO(ALTERA_IOC_MAGIC, 39)

#define IOCTL_GET_DATA_MSG_BUFFER_SIZE _IO(ALTERA_IOC_MAGIC, 30)
#define IOCTL_TX_BUFFER_CNT            _IO(ALTERA_IOC_MAGIC, 31)
#define IOCTL_RX_BUFFER_CNT            _IO(ALTERA_IOC_MAGIC, 32)

#define IOCTL_GET_RX_DEV_DDR_SIZE _IO(ALTERA_IOC_MAGIC, 40)
#define IOCTL_GET_RX_DEV_DDR_FILL _IO(ALTERA_IOC_MAGIC, 41)
#define IOCTL_GET_TX_DEV_DDR_SIZE _IO(ALTERA_IOC_MAGIC, 42)
#define IOCTL_GET_TX_DEV_DDR_FILL _IO(ALTERA_IOC_MAGIC, 43)
#define IOCTL_GET_RX_DEV_MAX_DATA_SIZE _IO(ALTERA_IOC_MAGIC, 44)
#define IOCTL_SET_RX_DEV_MAX_DATA_SIZE _IO(ALTERA_IOC_MAGIC, 48)

#define IOCTL_GET_FPGA_NUM_MSGS   _IO(ALTERA_IOC_MAGIC, 60)
#define IOCTL_GET_TX_HEAD         _IO(ALTERA_IOC_MAGIC, 61)
#define IOCTL_GET_TX_TAIL         _IO(ALTERA_IOC_MAGIC, 62)
#define IOCTL_GET_RX_TAIL         _IO(ALTERA_IOC_MAGIC, 63)
#define IOCTL_GET_RX_HEAD         _IO(ALTERA_IOC_MAGIC, 64)

#define IOCTL_RX_CLEAR_DATA       _IO(ALTERA_IOC_MAGIC, 97)
#define IOCTL_RX_CLEAR_CTRL       _IO(ALTERA_IOC_MAGIC, 98)
#define IOCTL_TX_RESET            _IO(ALTERA_IOC_MAGIC, 99)

#ifndef __KERNEL__

#include <sys/ioctl.h>

#endif

#endif /* _VXSDR_DMA_CMD_H */
